---
- name: Install PHP
  hosts: LAMP
  tasks:
    - name: install epel-release
      yum:
        name: epel-release
        state: latest
    - name: install yum-utils
      yum:
        name: yum-utils
        state: latest
    - name: Install PHP repository
      yum:
        name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: latest
    - name: Enable remi-php74 repository
      shell: yum-config-manager --enable remi-php74
    - name: install PHP with modules
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - php
          - php-common
          - php-mcrypt
          - php-cli
          - php-gd
          - php-curl
          - php-mysql
    - name: PHPInfo file 
      copy:
        src: /tmp/phpinfo.php
        dest: /var/www/html/
    - name: restart Apache service
      service:
        name: "httpd"
        state: restarted
        enabled: yes
