---
- name: MySql installation
  hosts: LAMP
  become: yes 
  vars_files:
    - vars/main.yml
  tasks:
  - name: Install MySQL repository
    yum:
      name: https://repo.mysql.com//mysql80-community-release-el7-7.noarch.rpm
      state: latest
 
  - name: Enable MySQL 8.0 repository
    shell: yum-config-manager --enable mysql80-community
 
  - name: Install MySQL packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - mysql-community-server
        - mysql-community-client
        - MySQL-python
 
  - name: Enable the MySQL service
    service:
      name: mysqld
      state: started
      enabled: true
  - name: Acquire temporary root password
    shell: "awk -F': ' '$0 ~ \"temporary password\"{print $2}' /var/log/mysqld.log"
    register: mysql_root_password_temp
  - name: Set new root password from default temporary password
    shell: "mysql -e \"SET PASSWORD = '{{ passwd_mysql_root }}';\"
         --connect-expired-password -uroot -p'{{ mysql_root_password_temp.stdout }}'
         && touch /root/.my.password.changed"
    args:
      creates: /root/.my.password.changed
  - name: Create /etc/my.cnf
    template:
      src: dbfiles/mysql.cnf.j2
      dest: /etc/my.cnf
      owner: root
      group: root
      mode: 0644
      backup: true
  - name: Restart the MySQL service
    service:
      name: mysqld
      state: restarted
